"""Add provider column to users table

Revision ID: 5d6ab53def05
Revises: 497dd4d9bf0d
Create Date: 2025-11-03 11:10:58.622517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6ab53def05'
down_revision: Union[str, Sequence[str], None] = '497dd4d9bf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
